theme: jekyll-theme-cayman
title: Photo Memory
description: Play memory with your photos!
logo: /images/CardBack.png
show_downloads: false

github:
  is_project_page: false
  
# About/contact
author:
  name:       Peter Kurzok © 2020
  url:        https://peterkurzok.de
